name: build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Start Report
        uses: Ilshidur/action-discord@master
        if: always()
        with:
          args: '{{ GITHUB_ACTION }} start for {{ EVENT_PAYLOAD.repository.full_name }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          skip-go-installation: true

      - name: Build
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --snapshot --rm-dist

      - name: Discord Finish Report
        uses: Ilshidur/action-discord@master
        if: always()
        with:
          args: '{{ GITHUB_ACTION }} finish for {{ EVENT_PAYLOAD.repository.full_name }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
