name: goreleaser

on:
  push:
    tags:
      - v*

env:
  dockerpushrm_version: "1.7.0"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Start Report
        uses: Ilshidur/action-discord@master
        if: always()
        with:
          args: '{{ GITHUB_ACTION }} start for {{ EVENT_PAYLOAD.repository.full_name }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login Github Container Registry
        id: githubContainerRegistryLogin
        uses: docker/login-action@v1.14.1
        with:
          registry: "ghcr.io"
          username: "jkaflik"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          skip-go-installation: true

      - name: Create Release
        id: createRelease
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord Finish Report
        uses: Ilshidur/action-discord@master
        if: always()
        with:
          args: '{{ GITHUB_ACTION }} finish for {{ EVENT_PAYLOAD.repository.full_name }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
